language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq -y update

install:
    - sudo apt-get -qq -y install libsdl2-dev libsdl2-ttf-dev libalut-dev libpng12-dev zlib1g-dev
    - if [ "$CC" = "gcc" ]; then sudo apt-get install gcc-4.8; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi

before_script:
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
    - (mkdir build && cd build && cmake .. && make)

notifications:
    irc:
        channels:
            - "chat.freenode.net#OpenRaider"
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

os:
    - linux
#     - osx
