language: cpp

compiler:
    - clang

before_install:
    - sudo add-apt-repository ppa:zoogie/sdl2-snapshots
    - sudo apt-get -qq -y update

install:
    - sudo apt-get -qq -y install libsdl2 libsdl2-ttf libalut-dev libpng12-dev zlib1g-dev

script:
    - (mkdir build && cd build && cmake .. && make)

notifications:
    irc:
        channels:
            - "chat.freenode.net#OpenRaider"
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

os:
    - linux
#     - osx
