language: cpp

compiler:
    - clang
    - gcc

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake/travis_before_install_linux.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake/travis_before_install_mac.sh; fi

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake/travis_install_linux.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake/travis_install_mac.sh; fi

before_script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake/travis_before_script_linux.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake/travis_before_script_mac.sh; fi

script:
    - (mkdir build && cd build && cmake .. && make)

notifications:
    irc:
        channels:
            - "chat.freenode.net#OpenRaider"
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

os:
    - linux
#     - osx
